name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'record-room/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_YOUTUBE_API_KEY: ${{ secrets.NEXT_PUBLIC_YOUTUBE_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: record-room/package-lock.json
      - name: Install dependencies
        working-directory: record-room
        run: npm ci
      - name: Build with Next.js
        working-directory: record-room
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: record-room/out
          branch: gh-pages
          target-folder: record-room